### ISSUE TITLE
It's better to set default_value of "assume_arags" to "underscore"???

### ISSUE THREAD

**Issue by kegao1** [algorys/cmakeconverter#51]
In visual_studio/vfproj/flags.py, I think maybe it's better to set default_value of "assume_arags" to "underscore" (line 234)? The default of Intel Fortran is "-assume underscore". Correct me if I'm wrong.

**Comment by pavelliavonau** [comment]
As you can see from https://software.intel.com/en-us/node/678222 default value is different for windows ans linux:

> Windows: nounderscore
Linux and OS X: underscore

Therefore I must make difference for default values for diff OS, but not I haven't support of this feature.
The main aim of converter is to provide equivalent of cmake scripts for given solution. Because of this I used default value for Windows.
You can always set explicit this parameter in your solution before conversion.
If you are not agree - I 'm waiting for your points and proposals).

**Comment by kegao1** [comment]
It's OK to just leave it as is, and let the user decide which default they're going to use based on their intended platform. Anyway, very useful package. Thanks for your work.

**Comment by pavelliavonau** [comment]
@kegao1 , I decieded to remove forcing this option. For Windows it's ok anyway but on linux it might be forced with GlobalSettings.cmake
